### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by iGetUploaded** [kekst/socialnuke#2]
Would be helpful if I knew how to run it all I get when I do is 
![image](https://user-images.githubusercontent.com/54633753/169428037-23fec132-2576-4281-b26e-e63d0f012dac.png)

**Comment by kekst** [comment]
switch to a good operating system (linux/macos) :^)
or just do yarn and then yarn start

**Comment by iGetUploaded** [comment]
Got it to work thanks... for some reason my computer was blocking yarn from actually running the install
